repos:
  - repo: local
    hooks:
      - id: update-tfvars-owner
        name: Update TFVars Owner
        entry: python3 hooks/main.py
        language: python
        files: ^z_test/.*\.tfvars$
        always_run: true
        pass_filenames: false
